apiVersion: v1
kind: Service
metadata:
  name: swc-demo-service
  labels:
    app: swc-demo
    role: service
    tier: backend
spec:
  selector:
    app: swc-demo
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: LoadBalancer