apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: swc-demo
    role: service
    tier: database
spec:
  selector:
    app: swc-demo
    role: persistence
    tier: database
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP

