apiVersion: v1
kind: Service
metadata:
  name: config
  labels:
    app: swc-demo
    role: config
    tier: database
spec:
  selector:
    app: swc-demo
    role: config
    tier: database
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
  type: LoadBalancer

