apiVersion: v1
kind: Service
metadata:
  name: wp-demo-db-service
  labels:
    app: wp-demo
    role: service
    tier: backend
spec:
  selector:
    app: wp-demo
    role: db
    tier: backend
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  type: NodePort