apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-demo-wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-demo
      role: cms
      tier: backend
  template:
    metadata:
      labels:
        app: wp-demo
        role: cms
        tier: backend
    spec:
      containers:
      - name: admin
        image: wordpress
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: wp-demo-db-service.default.svc.cluster.local
        - name: WORDPRESS_DB_USER
          value: utm
        - name: WORDPRESS_DB_PASSWORD
          value: utm!
        - name: WORDPRESS_DB_NAME
          value: wp
